version: "3.1"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./app:/var/www/html

  database:
    image: "mariadb"
    restart: always
    environment:
      MYSQL_DATABASE: data
      MYSQL_ROOT_PASSWORD: password
    volumes:
      # Pour lancer un dump automatiquement au montage du conteneur
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - "1333:8080"
